### ISSUE TITLE
Unknown func bpf_skb_load_bytes

### ISSUE THREAD

**Issue by toasthorse** [foniod/redbpf#220] opened 2021-11-14 16:08 UTC
Hello,

I first followed the tutorial to get started with redbpf which worked very nicely. I then used the tutorial template and changed it to hook into the kernel function `__dev_queue_xmit` to read properties of network packets being transmitted. Compilation works without errors but the program panicks when trying to load the probe program. In the probe program, I use the `struct SkBuff` from `redbpf_probes::socket::SkBuff`, which internally calls `bpf_skb_load_bytes`. When running it, it panicks with the error `"unknown func bpf_skb_load_bytes"`:
```
     Running `target/debug/redbpf-tutorial`
Nov 14 16:52:30.587 ERROR redbpf: error loading BPF program `__dev_queue_xmit' with bpf_load_program_xattr. ret=-1 os error=Invalid argument (os error 22): 0: (bf) r6 = r1
1: (b7) r8 = 0
2: (63) *(u32 *)(r10 -24) = r8
last_idx 2 first_idx 0
regs=100 stack=0 before 1: (b7) r8 = 0
3: (7b) *(u64 *)(r10 -32) = r8
4: (7b) *(u64 *)(r10 -40) = r8
5: (7b) *(u64 *)(r10 -48) = r8
6: (7b) *(u64 *)(r10 -56) = r8
7: (7b) *(u64 *)(r10 -64) = r8
8: (7b) *(u64 *)(r10 -72) = r8
9: (7b) *(u64 *)(r10 -80) = r8
10: (7b) *(u64 *)(r10 -88) = r8
11: (7b) *(u64 *)(r10 -96) = r8
12: (7b) *(u64 *)(r10 -104) = r8
13: (7b) *(u64 *)(r10 -112) = r8
14: (7b) *(u64 *)(r10 -120) = r8
15: (7b) *(u64 *)(r10 -128) = r8
16: (7b) *(u64 *)(r10 -136) = r8
17: (7b) *(u64 *)(r10 -144) = r8
18: (79) r7 = *(u64 *)(r6 +112)
19: (85) call bpf_ktime_get_ns#5
20: (7b) *(u64 *)(r10 -160) = r0
21: (85) call bpf_get_current_pid_tgid#14
22: (7b) *(u64 *)(r10 -152) = r0
23: (7b) *(u64 *)(r10 -8) = r8
24: (7b) *(u64 *)(r10 -16) = r8
25: (bf) r1 = r10
26: (07) r1 += -16
27: (b7) r2 = 16
28: (85) call bpf_get_current_comm#16
last_idx 28 first_idx 22
regs=4 stack=0 before 27: (b7) r2 = 16
29: (79) r1 = *(u64 *)(r10 -8)
30: (7b) *(u64 *)(r10 -128) = r1
31: (79) r1 = *(u64 *)(r10 -16)
32: (7b) *(u64 *)(r10 -136) = r1
33: (bf) r3 = r10
34: (07) r3 += -16
35: (bf) r1 = r7
36: (b7) r2 = 0
37: (b7) r4 = 4
38: (85) call bpf_skb_load_bytes#26
unknown func bpf_skb_load_bytes#26
processed 39 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 1

thread 'main' panicked at 'error on Loader::load: LoadError("__dev_queue_xmit", BPF)', src/main.rs:22:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

```

I am not quite sure what the issue is here, I'd really appreciate any help!

This is my system info:
```
rustc 1.56.1
llvm 13.0.0-3
Kernel: Linux 5.10.78-1-lts
```

**Comment by rhdxmr** [comment] 2021-11-14 17:30
Hello @toasthorse 

Specific type of BPF program can call only part of BPF helper functions.
The `bpf_skb_load_bytes` BPF helper function is allowed to some BPF program types: socket filter, tc cls act, sk skb, lwt out.

But XDP type BPF program is not allowed to call `bpf_skb_load_bytes`.
See kernel source for more information: 
- https://elixir.bootlin.com/linux/v5.10.78/source/net/core/filter.c#L7206
- https://elixir.bootlin.com/linux/v5.10.78/source/kernel/bpf/verifier.c#L5329

**Comment by toasthorse** [comment] 2021-11-14 19:55
Hi @rhdxmr, thanks for your answer! In my probe main.rs I use `#[kprobe("__dev_queue_xmit")] before declaring my probe function. I am assuming this means kprobe cannot use this function then, right?
I tried using the `bpf_probe_read_kernel` function instead of `load` to extract a field from the `sk_buff` but I cannot seem to cast a `&u32` to a `*mut c_void` to use this function properly. Is this the right approach?

**Comment by rhdxmr** [comment] 2021-11-15 08:08
@toasthorse 

If the type of your BPF program is kprobe, then the context of the BPF program should be `Registers`.
See this [example code]( https://github.com/foniod/redbpf/blob/cc407bf04298263653cf5b98677bcf0a84bb633e/examples/example-probes/src/biolatpcts/main.rs#L31) for more information.

As a BPF terminology, the `context` means the parameter passed to the BPF program. And each type of BPF program has corresponding context. The context passed to kprobe BPF programs is registers.

You can get the first parameter passed to `__dev_queue_xmit` by calling `Registers::parm1()` and second parameter using `Registers::parm2()` and so on.

And if the target kernel function is inlined, attaching to that function won't work.

**Comment by rhdxmr** [comment] 2021-11-15 08:17
@toasthorse 
If you have a few more problems, please let me know. And I guess I can help you better if I see your code. So if you don't mind, attach your code with your question.

**Comment by toasthorse** [comment] 2021-11-15 19:08
@rhdxmr Thank you for your help with this, I really appreciate it!
This is my probe main.rs file:
```
#![no_std]
#![no_main]

// use one of the preludes
use redbpf_probes::kprobe::prelude::*;
use redbpf_probes::socket::{SkBuff, SocketError};
use redbpf_probes::socket_filter::{SkBuffAction, SkBuffResult};
use memoffset::offset_of;
use core::convert::TryInto;
use core::mem::size_of;
use core::ptr;
// Use the types you're going to share with userspace, eg:
use probes::openmonitor::*;

program!(0xFFFFFFFE, "GPL");

#[map]
static mut kernel_events: PerfMap<XmitEvent> = PerfMap::with_max_entries(2048);

#[kprobe("__dev_queue_xmit")]
fn dev_queue_xmit(regs: Registers) -> SkBuffResult {
    let mut event = XmitEvent::default();
    unsafe {
        let skb = SkBuff {
            skb: regs.parm1() as *const __sk_buff,
        };
        event.timestamp = bpf_ktime_get_ns();
        let pid_tgid = bpf_get_current_pid_tgid();
        event.pid = pid_tgid as u32;
        event.tgid = (pid_tgid >> 32) as u32;
        event.command = bpf_get_current_comm();

        // event.len = skb.load(offset_of!(__sk_buff, len))?;
        // let datalen:u32 = skb.load(offset_of!(__sk_buff, wire_len))?;

        let len_ptr: *const u32 = (skb.skb as usize + offset_of!(__sk_buff, len)) as *const u32;
        event.len = ptr::read(len_ptr);
        let datalen_ptr: *const u32 = (skb.skb as usize + offset_of!(__sk_buff, len)) as *const u32;
        let datalen = ptr::read(datalen_ptr);

        // let mut datalen:u32 = 0;
        // let ok = bpf_probe_read_kernel(
        //     &datalen as *mut _,
        //     size_of::<u32>().try_into().unwrap(),
        //     (*skb.skb).wire_len as *const _
        // );
        // if ok != 0 {
        //     return Err(SocketError::LoadFailed);
        // }


        // let ok = bpf_probe_read_kernel(
        //     &event.len as *mut _,
        //     size_of::<u32>().try_into().unwrap(),
        //     (*skb.skb).len as *const _
        // );
        // if ok != 0 {
        //     return Err(SocketError::LoadFailed);
        // }


        let actuallen:u32 = event.len - datalen;
        
        let readlen = match actuallen < BUFSIZE.try_into().unwrap() {
            true => actuallen,
            false => BUFSIZE.try_into().unwrap(),
        };

        //use regular bpf function to read only part of the data, not everything
        let ok = bpf_probe_read_kernel(
            event.data.as_mut_ptr() as *mut _,
            readlen.try_into().unwrap(),
            (*skb.skb).data as *const _,
            );
        if ok != 0 {
            return Err(SocketError::LoadFailed);
        }

        event.copied_len = readlen;
        kernel_events.insert(regs.ctx, &event);
        
        Ok(SkBuffAction::SendToUserspace)
    }
}

```

The `skb.load` statements which are commented out are the ones which produced the error with `bpf_skb_load_bytes`. Therefore my second approach was to use `bpf_probe_read_kernel` to read the `len` field of the `__sk_buff` struct (commented out here). In the first argument to that function, e.g. `&datalen as *mut _`, it won't let me cast `&u32` to a `*mut c_void`.
Then I tried to access the fields directly by copying the pointer and dereferencing it with `ptr::read`. This will compile but at runtime will fail with the error `invalid mem access 'inv'`.

I also just tried executing the last `bpf_probe_read_kernel` function to see if reading the data works at least, but that one also fails with `invalid mem access 'inv'`. So it seems there is an issue with reading from the `__sk_buff` struct overall somehow.

The XmitEvent is a struct I use in `mod.rs` where I define a few fields like `len, timestamp, pid` and so on to pass this info to userspace.

Is this the wrong approach?

**Comment by rhdxmr** [comment] 2021-11-17 09:14
@toasthorse 
Sorry for the late response.
I took the second shot of Moderna vaccine yesterday so I felt sick since last
night. And I got better after couple of hours ago.
 
I read your code and I corrected your code.
I give you a few background knowledge.

* kprobe BPF program does not return anything
* struct `__sk_buff` is different from struct `sk_buff`. `__sk_buff` is a view
  of `sk_buff` and `__sk_buff` is provided by BPF infrastructure. In some BPF
  program types, BPF infrastructure passes `__sk_buff` to the BPF program as a
  context.


BPF program
```rust
#![no_std]
#![no_main]
use probes::devqueue::XmitEvent;
use redbpf_probes::kprobe::prelude::*;

program!(0xFFFFFFFE, "GPL");

use core::mem::{self, MaybeUninit};
#[map]
static mut XMIT_EVENTS: PerfMap<XmitEvent> = PerfMap::with_max_entries(2048);

#[map]
static mut DATA_BUF: PerCpuArray<XmitEvent> = PerCpuArray::with_max_entries(1);

#[kprobe("__dev_queue_xmit")]
unsafe fn dev_queue_xmit(regs: Registers) {
    let buf = DATA_BUF.get_mut(0).unwrap();
    buf.timestamp = bpf_ktime_get_ns();
    buf.pid = (bpf_get_current_pid_tgid() >> 32) as u32;
    buf.tgid = (bpf_get_current_pid_tgid() & 0xFFFFFFFF) as u32;
    buf.command = bpf_get_current_comm();
    let skbptr = regs.parm1() as *const u64 as *const sk_buff;
    let mut skb = MaybeUninit::<sk_buff>::uninit();
    if bpf_probe_read_kernel(
        skb.as_mut_ptr() as *mut _,
        mem::size_of::<sk_buff>() as u32,
        skbptr as *const _,
    ) < 0
    {
        bpf_trace_printk(b"error read skb\0");
        return;
    }
    let skb = skb.assume_init();
    buf.data_len = skb.data_len % 4096;
    if bpf_probe_read_kernel(
        buf.data.as_mut_ptr() as *mut _,
        buf.data_len,
        skb.data as *const _,
    ) < 0
    {
        bpf_trace_printk(b"error read data\0");
        return;
    }

    XMIT_EVENTS.insert(regs.ctx, buf);

    bpf_trace_printk(b"hello\0");
}

```


userspace program
```rust
use futures::stream::StreamExt;

use std::ptr;
use tokio::signal::ctrl_c;
use tracing::Level;
use tracing_subscriber::FmtSubscriber;

use probes::devqueue::XmitEvent;
use redbpf::{self, load::Loader};

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let subscriber = FmtSubscriber::builder()
        .with_max_level(Level::WARN)
        .finish();
    tracing::subscriber::set_global_default(subscriber).unwrap();

    let mut loaded = Loader::load(probe_code()).expect("error on Loader::load");
    loaded
        .kprobe_mut("__dev_queue_xmit")
        .unwrap()
        .attach_kprobe("__dev_queue_xmit", 0)
        .unwrap();
    while let Some((name, events)) = loaded.events.next().await {
        for event in events {
            if name.as_str() == "XMIT_EVENTS" {
                let xmit_event = unsafe { ptr::read_unaligned(event.as_ptr() as *const XmitEvent) };
                println!("{} {}", xmit_event.pid, xmit_event.data_len);
            }
        }
    }
    ctrl_c().await;
}

fn probe_code() -> &'static [u8] {
    include_bytes!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/target/bpf/programs/devqueue/devqueue.elf"
    ))
}
```


But I am not an expert of network subsystem of the Linux kernel. And I can't
guarantee that the BPF program I wrote makes sense. Because I am not sure about
the meaning of each fields of `struct sk_buff` and reading `skb.data` directly
is the correct way for reading whole data. Maybe there are special kernel
functions that correctly read data from the `skb.data` pointer.

If you have an issue please feel free to ask me anything. And if you are
willing to explain what is the correct way of reading data from the `struct
sk_buff`, please let me know.

Thanks,

**Comment by rhdxmr** [comment] 2021-11-17 09:16
Ah.. I missed the `mod.rs` of the probes. Here it is:

```rust
#[repr(C)]
#[derive(Debug, Clone)]
pub struct XmitEvent {
    pub timestamp: u64,
    pub pid: u32,
    pub tgid: u32,
    pub command: [i8; 16],
    pub data: [u8; 4096],
    pub data_len: u32,
}
```

**Comment by toasthorse** [comment] 2021-11-17 21:00
@rhdxmr No need to apologize, glad to hear you're feeling better. Health comes first!

Firstly, thank you for taking the time to write this out!
So I observed something peculiar. I first replaced the contents of BPF program, the userspace program and the `mod.rs` probe file with your code (I only replaced the `devqueue` path to the previous name). After compiling both the probe and userspace program, it worked nicely and printed the PIDs and the `data_len` field.

I then expanded this by adding the `len` field to the `struct XmitEvent` since this is another relevant field of `struct sk_buff` and attempted to read it, once by directly accessing it with `skb.len` and once with `bpf_probe_read_kernel` but ran into a permission error both times. I then undid all my changes but the permission error persists, even though the source is exactly as before when it was working. This is the complete output when I try to run it now:
```
warning: unused `Result` that must be used
  --> src/main.rs:32:5
   |
32 |     ctrl_c().await;
   |     ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled

warning: `redbpf-tutorial` (bin "redbpf-tutorial") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/redbpf-tutorial`
Nov 17 21:50:41.881 ERROR redbpf::btf: error on bpf_load_btf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 1008
str_off: 1008
str_len: 1724
btf_total_size: 2756
[1] PTR (anon) type_id=2
[2] INT u8 size=1 bits_offset=0 nr_bits=8 encoding=(none)
[3] PTR (anon) type_id=2
[4] INT usize size=8 bits_offset=0 nr_bits=64 encoding=(none)
[5] FUNC_PROTO (anon) return=1 args=(1 dest, 3 src, 4 n)
[6] FUNC memcpy type_id=5
[7] FUNC_PROTO (anon) return=1 args=(1 dest, 3 src, 4 n)
[8] FUNC memmove type_id=7
[9] INT i32 size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[10] FUNC_PROTO (anon) return=1 args=(1 s, 9 c, 4 n)
[11] FUNC memset type_id=10
[12] FUNC_PROTO (anon) return=9 args=(3 s1, 3 s2, 4 n)
[13] FUNC memcmp type_id=12
[14] FUNC_PROTO (anon) return=9 args=(3 s1, 3 s2, 4 n)
[15] FUNC bcmp type_id=14
[16] PTR (anon) type_id=17
[17] ENUM c_void size=1 vlen=2
	__variant1 val=0
	__variant2 val=1
[18] FUNC_PROTO (anon) return=9 args=(16 ctx)
[19] FUNC outer_dev_queue_xmit type_id=18
[20] ARRAY (anon) type_id=2 index_type_id=21 nr_elems=4
[21] INT __ARRAY_SIZE_TYPE__ size=4 bits_offset=0 nr_bits=32 encoding=(none)
[22] VAR _license type_id=20 linkage=1
[23] INT u32 size=4 bits_offset=0 nr_bits=32 encoding=(none)
[24] VAR _version type_id=23 linkage=1
[25] STRUCT PerfMap_probes__openmonitor__XmitEvent_ size=20 vlen=2
	def type_id=26 bits_offset=0
	_event type_id=27 bits_offset=0
[26] STRUCT bpf_map_def size=20 vlen=5
	type_ type_id=23 bits_offset=0
	key_size type_id=23 bits_offset=32
	value_size type_id=23 bits_offset=64
	max_entries type_id=23 bits_offset=96
	map_flags type_id=23 bits_offset=128
[27] STRUCT PhantomData_probes__openmonitor__XmitEvent_ size=0 vlen=0
[28] VAR XMIT_EVENTS type_id=25 linkage=1
[29] STRUCT PerCpuArray_probes__openmonitor__XmitEvent_ size=20 vlen=2
	def type_id=26 bits_offset=0
	_element type_id=27 bits_offset=0
[30] VAR DATA_BUF type_id=29 linkage=1
[31] STRUCT MapBtf size=64 vlen=2
	key_type type_id=23 bits_offset=0
	value_type type_id=32 bits_offset=64
[32] STRUCT XmitEvent size=56 vlen=6
	timestamp type_id=33 bits_offset=0
	pid type_id=23 bits_offset=64
	tgid type_id=23 bits_offset=96
	command type_id=35 bits_offset=128
	data type_id=36 bits_offset=256
	data_len type_id=23 bits_offset=384
[33] INT u64 size=8 bits_offset=0 nr_bits=64 encoding=(none)
[34] INT i8 size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[35] ARRAY (anon) type_id=34 index_type_id=21 nr_elems=16
[36] ARRAY (anon) type_id=2 index_type_id=21 nr_elems=15
[37] VAR MAP_BTF_DATA_BUF type_id=31 linkage=1
[38] DATASEC .rodata size=21 vlen=0 vlen == 0

Nov 17 21:50:41.906 ERROR redbpf: error loading BPF program `__dev_queue_xmit' with bpf_load_program_xattr. ret=-1 os error=Permission denied (os error 13): 0: (bf) r6 = r1
1: (b7) r8 = 0
2: (63) *(u32 *)(r10 -224) = r8
last_idx 2 first_idx 0
regs=100 stack=0 before 1: (b7) r8 = 0
3: (bf) r2 = r10
4: (07) r2 += -224
5: (18) r1 = 0xffff9e551e23ce00
7: (85) call bpf_map_lookup_elem#1
8: (bf) r7 = r0
9: (55) if r7 != 0x0 goto pc+16

from 9 to 26: R0_w=map_value(id=0,off=0,ks=4,vs=56,imm=0) R6_w=ctx(id=0,off=0,imm=0) R7_w=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8_w=invP0 R10=fp0 fp-224=????mmmm
26: (85) call bpf_ktime_get_ns#5
27: (7b) *(u64 *)(r7 +0) = r0
 R0_w=inv(id=0) R6_w=ctx(id=0,off=0,imm=0) R7_w=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8_w=invP0 R10=fp0 fp-224=????mmmm
28: (85) call bpf_get_current_pid_tgid#14
29: (77) r0 >>= 32
30: (63) *(u32 *)(r7 +8) = r0
 R0_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6_w=ctx(id=0,off=0,imm=0) R7_w=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8_w=invP0 R10=fp0 fp-224=????mmmm
31: (85) call bpf_get_current_pid_tgid#14
32: (63) *(u32 *)(r7 +12) = r0
 R0_w=inv(id=0) R6_w=ctx(id=0,off=0,imm=0) R7_w=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8_w=invP0 R10=fp0 fp-224=????mmmm
33: (7b) *(u64 *)(r10 -216) = r8
34: (7b) *(u64 *)(r10 -224) = r8
35: (bf) r1 = r10
36: (07) r1 += -224
37: (b7) r2 = 16
38: (85) call bpf_get_current_comm#16
last_idx 38 first_idx 0
regs=4 stack=0 before 37: (b7) r2 = 16
39: (79) r1 = *(u64 *)(r10 -224)
40: (79) r2 = *(u64 *)(r10 -216)
41: (7b) *(u64 *)(r7 +24) = r2
 R0=inv(id=0) R1_w=inv(id=0) R2_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8=invP0 R10=fp0 fp-216=mmmmmmmm fp-224=mmmmmmmm
42: (7b) *(u64 *)(r7 +16) = r1
 R0=inv(id=0) R1_w=inv(id=0) R2_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8=invP0 R10=fp0 fp-216=mmmmmmmm fp-224=mmmmmmmm
43: (79) r3 = *(u64 *)(r6 +112)
44: (bf) r1 = r10
45: (07) r1 += -224
46: (b7) r2 = 224
47: (85) call bpf_probe_read_kernel#113
last_idx 47 first_idx 39
regs=4 stack=0 before 46: (b7) r2 = 224
48: (6d) if r8 s> r0 goto pc+21
 R0_w=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8=invP0 R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm fp-112=mmmmmmmm fp-120=mmmmmmmm fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=mmmmmmmm fp-152=mmmmmmmm fp-160=mmmmmmmm fp-168=mmmmmmmm fp-176=mmmmmmmm fp-184=mmmmmmmm fp-192=mmmmmmmm fp-200=mmmmmmmm fp-208=mmmmmmmm fp-216=mmmmmmmm fp-224=mmmmmmmm
49: (61) r2 = *(u32 *)(r10 -108)
50: (57) r2 &= 4095
51: (79) r3 = *(u64 *)(r10 -24)
52: (63) *(u32 *)(r7 +48) = r2
 R0_w=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R2_w=inv(id=0,umax_value=4095,var_off=(0x0; 0xfff)) R3_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8=invP0 R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm fp-112=mmmmmmmm fp-120=mmmmmmmm fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=mmmmmmmm fp-152=mmmmmmmm fp-160=mmmmmmmm fp-168=mmmmmmmm fp-176=mmmmmmmm fp-184=mmmmmmmm fp-192=mmmmmmmm fp-200=mmmmmmmm fp-208=mmmmmmmm fp-216=mmmmmmmm fp-224=mmmmmmmm
53: (bf) r1 = r7
54: (07) r1 += 32
55: (85) call bpf_probe_read_kernel#113
 R0_w=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R1_w=map_value(id=0,off=32,ks=4,vs=56,imm=0) R2_w=inv(id=0,umax_value=4095,var_off=(0x0; 0xfff)) R3_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8=invP0 R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm fp-112=mmmmmmmm fp-120=mmmmmmmm fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=mmmmmmmm fp-152=mmmmmmmm fp-160=mmmmmmmm fp-168=mmmmmmmm fp-176=mmmmmmmm fp-184=mmmmmmmm fp-192=mmmmmmmm fp-200=mmmmmmmm fp-208=mmmmmmmm fp-216=mmmmmmmm fp-224=mmmmmmmm
 R0_w=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R1_w=map_value(id=0,off=32,ks=4,vs=56,imm=0) R2_w=inv(id=0,umax_value=4095,var_off=(0x0; 0xfff)) R3_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=map_value(id=0,off=0,ks=4,vs=56,imm=0) R8=invP0 R10=fp0 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm fp-48=mmmmmmmm fp-56=mmmmmmmm fp-64=mmmmmmmm fp-72=mmmmmmmm fp-80=mmmmmmmm fp-88=mmmmmmmm fp-96=mmmmmmmm fp-104=mmmmmmmm fp-112=mmmmmmmm fp-120=mmmmmmmm fp-128=mmmmmmmm fp-136=mmmmmmmm fp-144=mmmmmmmm fp-152=mmmmmmmm fp-160=mmmmmmmm fp-168=mmmmmmmm fp-176=mmmmmmmm fp-184=mmmmmmmm fp-192=mmmmmmmm fp-200=mmmmmmmm fp-208=mmmmmmmm fp-216=mmmmmmmm fp-224=mmmmmmmm
invalid access to map value, value_size=56 off=32 size=4095
R1 min value is outside of the allowed memory range
processed 55 insns (limit 1000000) max_states_per_insn 0 total_states 2 peak_states 2 mark_read 1

thread 'main' panicked at 'error on Loader::load: LoadError("__dev_queue_xmit", BPF)', src/main.rs:18:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

As you can see in the error line after all the bracketed numbers, it returns a Permission denied error, despite previously running. I cleaned and recompiled everything (using `sudo`) to make sure everything was in order but it still happens. The source files are exactly as you posted them. Do you have an idea what could cause this?

**Comment by rhdxmr** [comment] 2021-11-18 09:41
@toasthorse 
Did you decrese the array length of `XmitEvent::data` to 16 or something?

This is what I posted before.
```rust
#[repr(C)]
#[derive(Debug, Clone)]
pub struct XmitEvent {
    pub timestamp: u64,
    pub pid: u32,
    pub tgid: u32,
    pub command: [i8; 16],
    pub data: [u8; 4096],
    pub data_len: u32,
}
```

The error message says that it is invalid to read memory out of value size.
```
invalid access to map value, value_size=56 off=32 size=4095
```
32 is offset of `XmitEvent::data` field.
4095 is read size that you passed to `bpf_probe_read_kernel` as the 2nd parameter.
56 is size of `XmitEvent` structure.

**Comment by toasthorse** [comment] 2021-11-18 10:14
You're right, I changed it to a lower size and completely overlooked changing the amount to be read after. Sorry!

I do have one more question regarding the buffer; what is the idea behind using something like a PerCpuArray to buffer data instead of directly instantiating the `struct XmitEvent` and then adding it to the PerfMap?

**Comment by rhdxmr** [comment] 2021-11-18 10:16
@toasthorse 
You should use `PerCpuArray` when you handle big size structures because bpf stack size limit is 512 bytes.

**Comment by toasthorse** [comment] 2021-11-18 10:20
@rhdxmr I see, that makes sense. Thank you for all your help!

**Comment by rhdxmr** [comment] 2021-11-18 10:24
@toasthorse 
You're welcome. Thanks for showing interest in RedBPF.

**Comment by rhdxmr** [comment] 2021-11-22 11:02
I'm closing this issue.
If you have any question related to this issue please feel free to re-open this.
Thanks,

**Closed by rhdxmr** 2021-11-22 11:02 UTC

**Comment by toasthorse** [comment] 2021-11-22 22:34
Hi @rhdxmr,
I did actually just run into another small problem regarding this. It compiles without errors but when running, I get the following error: `R2 min value is negative, either use unsigned or 'var &= const'`. This is the affected part (I am assuming `R2` refers to the second argument, `readlen`?):
```rust
    let mut readlen:u32 = min((skb.len - skb.data_len) % 100, BUFSIZE.try_into().unwrap());

    readlen &= 0x7FFFFFFF;

    if bpf_probe_read_kernel(
        event.data.as_mut_ptr() as *mut _,
        readlen as u32,
        skb.data as *const _,
    ) < 0
    {
        bpf_trace_printk(b"error reading skb.data\0");
    }
```
As you can see I tried both AND-ing it with a positive value and typecasting it but the error persists (I also tried them separately). I am doing this because I only want to read a certain number of bytes (<= 100) from the data contained in the skb.  This also happens when changing the size of the `data` field to 100 in your code, where there is no subtraction involved at all. With the previous size of 4096, it worked (for reference, `event` here is the same as `buf` in your code). Is there a way to make this work?

**Comment by rhdxmr** [comment] 2021-11-23 13:37
@toasthorse 
I can't reproduce your issue by copy&paste your code.
I guess the error occurs because of `skb.len - skb.data_len`. BPF verifier assume this expression can be a negative value.
How about checking the value explictly and correct it as below:
```rust
let len: u32 = if skb.len - skb.data_len < 0 {
    0
} else {
    skb.len - skb.data_len
};

let readlen: u32 = len % 100;
```

**Comment by rhdxmr** [comment] 2021-11-23 13:39
@toasthorse 
I just wonder what `skb.len - skb.data_len` means in the kernel network system?

**Comment by toasthorse** [comment] 2021-11-23 19:55
Okay I figured it out; the size of the `data` field needs to be a power of 2 for some reason. I set it to 128 and now it works.

In a socket buffer there is also paged data; the size of that is referenced by `skb.data_len`. I only want to read non-paged data, which is calculated with`skb.len` - `skb.data_len`. [Here](http://vger.kernel.org/~davem/skb_data.html) it is explained nicely.

**Comment by nitishm** [comment] 2021-12-30 20:35
> Hello @toasthorse
> 
> Specific type of BPF program can call only part of BPF helper functions. The `bpf_skb_load_bytes` BPF helper function is allowed to some BPF program types: socket filter, tc cls act, sk skb, lwt out.
> 
> But XDP type BPF program is not allowed to call `bpf_skb_load_bytes`. See kernel source for more information:
> 
> * https://elixir.bootlin.com/linux/v5.10.78/source/net/core/filter.c#L7206
> * https://elixir.bootlin.com/linux/v5.10.78/source/kernel/bpf/verifier.c#L5329

@rhdxmr I am new to eBPF. Regarding an XDP program how can I transmit data using maps to the userspace program from the BPF program?

**Comment by rhdxmr** [comment] 2021-12-31 16:40
Hi @nitishm 
I answered your question via the [PR](https://github.com/nitishm/xdp-flow-tuples/pull/1)
